### Pobierz wszystkie linie
GET http://rozklady.lodz.pl/Home/GetRouteList?ttId=0

### Pobierz konkretną linię pod routeId=401491 (linia 1)
GET http://rozklady.lodz.pl/Home/GetTracks?routeId=401491&ttId=0