### Pobierz wszystkie linie
GET http://rozklady.lodz.pl/Home/GetRouteList

### Pobierz konkretną linię pod routeId=401491 (linia 1)
GET http://rozklady.lodz.pl/Home/GetTracks?routeId=401491

### linia 45
GET http://rozklady.lodz.pl/Home/GetTracks?routeId=401536

### linia 91B
GET http://rozklady.lodz.pl/Home/GetTracks?routeId=401588